#!/usr/bin/env python3

import sys
from os import walk
import subprocess

paths=["/cress/.infra/boxes"]

def findExecutable(path,dest):
    for root, dirs, files in walk(path):
        for file in files:
            cpath=root + "/" + file
            if(file==dest or cpath==dest):return [cpath]

def run():
    args=sys.argv[1:len(sys.argv)]
    for path in paths:
        dest=args[0]
        executable=findExecutable(path,dest)
        if(executable):
            com_arr=executable + args[1:len(args)]
            coms_args=" ".join(com_arr)
            return subprocess.run(coms_args,shell=True,stdout=sys.stdout)

run()
